// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ProtocolModule.proto

package com.lianggzone.netty.entity;

public final class ProtocolModule {
  private ProtocolModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommonProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommonProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    boolean hasCommHeader();
    /**
     * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader getCommHeader();
    /**
     * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeaderOrBuilder getCommHeaderOrBuilder();

    /**
     * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    boolean hasLiveHeader();
    /**
     * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader getLiveHeader();
    /**
     * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeaderOrBuilder getLiveHeaderOrBuilder();

    /**
     * <code>optional bytes Data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes Data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code CommonProtocol}
   *
   * <pre>
   *公共头
   * </pre>
   */
  public static final class CommonProtocol extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CommonProtocol)
      CommonProtocolOrBuilder {
    // Use CommonProtocol.newBuilder() to construct.
    private CommonProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommonProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommonProtocol defaultInstance;
    public static CommonProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public CommonProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommonProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = commHeader_.toBuilder();
              }
              commHeader_ = input.readMessage(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(commHeader_);
                commHeader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = liveHeader_.toBuilder();
              }
              liveHeader_ = input.readMessage(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(liveHeader_);
                liveHeader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.class, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.Builder.class);
    }

    public static com.google.protobuf.Parser<CommonProtocol> PARSER =
        new com.google.protobuf.AbstractParser<CommonProtocol>() {
      public CommonProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonProtocol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommonProtocol> getParserForType() {
      return PARSER;
    }

    public interface CommonHeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CommonProtocol.CommonHeader)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required uint32 CommandId = 1;</code>
       */
      boolean hasCommandId();
      /**
       * <code>required uint32 CommandId = 1;</code>
       */
      int getCommandId();

      /**
       * <code>required uint32 SeqId = 2;</code>
       */
      boolean hasSeqId();
      /**
       * <code>required uint32 SeqId = 2;</code>
       */
      int getSeqId();

      /**
       * <code>required uint32 Version = 3;</code>
       */
      boolean hasVersion();
      /**
       * <code>required uint32 Version = 3;</code>
       */
      int getVersion();

      /**
       * <code>optional string FromUid = 4;</code>
       */
      boolean hasFromUid();
      /**
       * <code>optional string FromUid = 4;</code>
       */
      java.lang.String getFromUid();
      /**
       * <code>optional string FromUid = 4;</code>
       */
      com.google.protobuf.ByteString
          getFromUidBytes();
    }
    /**
     * Protobuf type {@code CommonProtocol.CommonHeader}
     */
    public static final class CommonHeader extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:CommonProtocol.CommonHeader)
        CommonHeaderOrBuilder {
      // Use CommonHeader.newBuilder() to construct.
      private CommonHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private CommonHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final CommonHeader defaultInstance;
      public static CommonHeader getDefaultInstance() {
        return defaultInstance;
      }

      public CommonHeader getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private CommonHeader(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                commandId_ = input.readUInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                seqId_ = input.readUInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                version_ = input.readUInt32();
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                fromUid_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_CommonHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_CommonHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.class, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.Builder.class);
      }

      public static com.google.protobuf.Parser<CommonHeader> PARSER =
          new com.google.protobuf.AbstractParser<CommonHeader>() {
        public CommonHeader parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CommonHeader(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<CommonHeader> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int COMMANDID_FIELD_NUMBER = 1;
      private int commandId_;
      /**
       * <code>required uint32 CommandId = 1;</code>
       */
      public boolean hasCommandId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 CommandId = 1;</code>
       */
      public int getCommandId() {
        return commandId_;
      }

      public static final int SEQID_FIELD_NUMBER = 2;
      private int seqId_;
      /**
       * <code>required uint32 SeqId = 2;</code>
       */
      public boolean hasSeqId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 SeqId = 2;</code>
       */
      public int getSeqId() {
        return seqId_;
      }

      public static final int VERSION_FIELD_NUMBER = 3;
      private int version_;
      /**
       * <code>required uint32 Version = 3;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 Version = 3;</code>
       */
      public int getVersion() {
        return version_;
      }

      public static final int FROMUID_FIELD_NUMBER = 4;
      private java.lang.Object fromUid_;
      /**
       * <code>optional string FromUid = 4;</code>
       */
      public boolean hasFromUid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string FromUid = 4;</code>
       */
      public java.lang.String getFromUid() {
        java.lang.Object ref = fromUid_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromUid_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string FromUid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromUidBytes() {
        java.lang.Object ref = fromUid_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        commandId_ = 0;
        seqId_ = 0;
        version_ = 0;
        fromUid_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasCommandId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSeqId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasVersion()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, commandId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, seqId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeUInt32(3, version_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getFromUidBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, commandId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, seqId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, version_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getFromUidBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CommonProtocol.CommonHeader}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CommonProtocol.CommonHeader)
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_CommonHeader_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_CommonHeader_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.class, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.Builder.class);
        }

        // Construct using com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          commandId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          seqId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          version_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          fromUid_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_CommonHeader_descriptor;
        }

        public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader getDefaultInstanceForType() {
          return com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.getDefaultInstance();
        }

        public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader build() {
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader buildPartial() {
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader result = new com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.commandId_ = commandId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.seqId_ = seqId_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.version_ = version_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.fromUid_ = fromUid_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader) {
            return mergeFrom((com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader other) {
          if (other == com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.getDefaultInstance()) return this;
          if (other.hasCommandId()) {
            setCommandId(other.getCommandId());
          }
          if (other.hasSeqId()) {
            setSeqId(other.getSeqId());
          }
          if (other.hasVersion()) {
            setVersion(other.getVersion());
          }
          if (other.hasFromUid()) {
            bitField0_ |= 0x00000008;
            fromUid_ = other.fromUid_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasCommandId()) {
            
            return false;
          }
          if (!hasSeqId()) {
            
            return false;
          }
          if (!hasVersion()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int commandId_ ;
        /**
         * <code>required uint32 CommandId = 1;</code>
         */
        public boolean hasCommandId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 CommandId = 1;</code>
         */
        public int getCommandId() {
          return commandId_;
        }
        /**
         * <code>required uint32 CommandId = 1;</code>
         */
        public Builder setCommandId(int value) {
          bitField0_ |= 0x00000001;
          commandId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 CommandId = 1;</code>
         */
        public Builder clearCommandId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          commandId_ = 0;
          onChanged();
          return this;
        }

        private int seqId_ ;
        /**
         * <code>required uint32 SeqId = 2;</code>
         */
        public boolean hasSeqId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required uint32 SeqId = 2;</code>
         */
        public int getSeqId() {
          return seqId_;
        }
        /**
         * <code>required uint32 SeqId = 2;</code>
         */
        public Builder setSeqId(int value) {
          bitField0_ |= 0x00000002;
          seqId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 SeqId = 2;</code>
         */
        public Builder clearSeqId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          seqId_ = 0;
          onChanged();
          return this;
        }

        private int version_ ;
        /**
         * <code>required uint32 Version = 3;</code>
         */
        public boolean hasVersion() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required uint32 Version = 3;</code>
         */
        public int getVersion() {
          return version_;
        }
        /**
         * <code>required uint32 Version = 3;</code>
         */
        public Builder setVersion(int value) {
          bitField0_ |= 0x00000004;
          version_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 Version = 3;</code>
         */
        public Builder clearVersion() {
          bitField0_ = (bitField0_ & ~0x00000004);
          version_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object fromUid_ = "";
        /**
         * <code>optional string FromUid = 4;</code>
         */
        public boolean hasFromUid() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string FromUid = 4;</code>
         */
        public java.lang.String getFromUid() {
          java.lang.Object ref = fromUid_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              fromUid_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string FromUid = 4;</code>
         */
        public com.google.protobuf.ByteString
            getFromUidBytes() {
          java.lang.Object ref = fromUid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            fromUid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string FromUid = 4;</code>
         */
        public Builder setFromUid(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          fromUid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string FromUid = 4;</code>
         */
        public Builder clearFromUid() {
          bitField0_ = (bitField0_ & ~0x00000008);
          fromUid_ = getDefaultInstance().getFromUid();
          onChanged();
          return this;
        }
        /**
         * <code>optional string FromUid = 4;</code>
         */
        public Builder setFromUidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          fromUid_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:CommonProtocol.CommonHeader)
      }

      static {
        defaultInstance = new CommonHeader(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:CommonProtocol.CommonHeader)
    }

    public interface LiveCommonHeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CommonProtocol.LiveCommonHeader)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required uint32 LiveType = 1;</code>
       *
       * <pre>
       * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
       * </pre>
       */
      boolean hasLiveType();
      /**
       * <code>required uint32 LiveType = 1;</code>
       *
       * <pre>
       * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
       * </pre>
       */
      int getLiveType();

      /**
       * <code>required uint32 LiveId = 2;</code>
       */
      boolean hasLiveId();
      /**
       * <code>required uint32 LiveId = 2;</code>
       */
      int getLiveId();

      /**
       * <code>required uint32 DemandType = 3;</code>
       *
       * <pre>
       * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
       * </pre>
       */
      boolean hasDemandType();
      /**
       * <code>required uint32 DemandType = 3;</code>
       *
       * <pre>
       * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
       * </pre>
       */
      int getDemandType();

      /**
       * <code>required uint32 DemandId = 4;</code>
       */
      boolean hasDemandId();
      /**
       * <code>required uint32 DemandId = 4;</code>
       */
      int getDemandId();

      /**
       * <code>optional uint32 ToDemandId = 5;</code>
       */
      boolean hasToDemandId();
      /**
       * <code>optional uint32 ToDemandId = 5;</code>
       */
      int getToDemandId();

      /**
       * <code>optional uint32 ToDemandType = 6;</code>
       */
      boolean hasToDemandType();
      /**
       * <code>optional uint32 ToDemandType = 6;</code>
       */
      int getToDemandType();
    }
    /**
     * Protobuf type {@code CommonProtocol.LiveCommonHeader}
     */
    public static final class LiveCommonHeader extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:CommonProtocol.LiveCommonHeader)
        LiveCommonHeaderOrBuilder {
      // Use LiveCommonHeader.newBuilder() to construct.
      private LiveCommonHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private LiveCommonHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final LiveCommonHeader defaultInstance;
      public static LiveCommonHeader getDefaultInstance() {
        return defaultInstance;
      }

      public LiveCommonHeader getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private LiveCommonHeader(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                liveType_ = input.readUInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                liveId_ = input.readUInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                demandType_ = input.readUInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                demandId_ = input.readUInt32();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                toDemandId_ = input.readUInt32();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                toDemandType_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_LiveCommonHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_LiveCommonHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.class, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.Builder.class);
      }

      public static com.google.protobuf.Parser<LiveCommonHeader> PARSER =
          new com.google.protobuf.AbstractParser<LiveCommonHeader>() {
        public LiveCommonHeader parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LiveCommonHeader(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<LiveCommonHeader> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int LIVETYPE_FIELD_NUMBER = 1;
      private int liveType_;
      /**
       * <code>required uint32 LiveType = 1;</code>
       *
       * <pre>
       * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
       * </pre>
       */
      public boolean hasLiveType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 LiveType = 1;</code>
       *
       * <pre>
       * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
       * </pre>
       */
      public int getLiveType() {
        return liveType_;
      }

      public static final int LIVEID_FIELD_NUMBER = 2;
      private int liveId_;
      /**
       * <code>required uint32 LiveId = 2;</code>
       */
      public boolean hasLiveId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 LiveId = 2;</code>
       */
      public int getLiveId() {
        return liveId_;
      }

      public static final int DEMANDTYPE_FIELD_NUMBER = 3;
      private int demandType_;
      /**
       * <code>required uint32 DemandType = 3;</code>
       *
       * <pre>
       * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
       * </pre>
       */
      public boolean hasDemandType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 DemandType = 3;</code>
       *
       * <pre>
       * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
       * </pre>
       */
      public int getDemandType() {
        return demandType_;
      }

      public static final int DEMANDID_FIELD_NUMBER = 4;
      private int demandId_;
      /**
       * <code>required uint32 DemandId = 4;</code>
       */
      public boolean hasDemandId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 DemandId = 4;</code>
       */
      public int getDemandId() {
        return demandId_;
      }

      public static final int TODEMANDID_FIELD_NUMBER = 5;
      private int toDemandId_;
      /**
       * <code>optional uint32 ToDemandId = 5;</code>
       */
      public boolean hasToDemandId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 ToDemandId = 5;</code>
       */
      public int getToDemandId() {
        return toDemandId_;
      }

      public static final int TODEMANDTYPE_FIELD_NUMBER = 6;
      private int toDemandType_;
      /**
       * <code>optional uint32 ToDemandType = 6;</code>
       */
      public boolean hasToDemandType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 ToDemandType = 6;</code>
       */
      public int getToDemandType() {
        return toDemandType_;
      }

      private void initFields() {
        liveType_ = 0;
        liveId_ = 0;
        demandType_ = 0;
        demandId_ = 0;
        toDemandId_ = 0;
        toDemandType_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasLiveType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLiveId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDemandType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDemandId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, liveType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, liveId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeUInt32(3, demandType_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeUInt32(4, demandId_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeUInt32(5, toDemandId_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeUInt32(6, toDemandType_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, liveType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, liveId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, demandType_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, demandId_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(5, toDemandId_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(6, toDemandType_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CommonProtocol.LiveCommonHeader}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CommonProtocol.LiveCommonHeader)
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_LiveCommonHeader_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_LiveCommonHeader_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.class, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.Builder.class);
        }

        // Construct using com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          liveType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          liveId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          demandType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          demandId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          toDemandId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          toDemandType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_LiveCommonHeader_descriptor;
        }

        public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader getDefaultInstanceForType() {
          return com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.getDefaultInstance();
        }

        public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader build() {
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader buildPartial() {
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader result = new com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.liveType_ = liveType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.liveId_ = liveId_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.demandType_ = demandType_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.demandId_ = demandId_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.toDemandId_ = toDemandId_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.toDemandType_ = toDemandType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader) {
            return mergeFrom((com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader other) {
          if (other == com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.getDefaultInstance()) return this;
          if (other.hasLiveType()) {
            setLiveType(other.getLiveType());
          }
          if (other.hasLiveId()) {
            setLiveId(other.getLiveId());
          }
          if (other.hasDemandType()) {
            setDemandType(other.getDemandType());
          }
          if (other.hasDemandId()) {
            setDemandId(other.getDemandId());
          }
          if (other.hasToDemandId()) {
            setToDemandId(other.getToDemandId());
          }
          if (other.hasToDemandType()) {
            setToDemandType(other.getToDemandType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasLiveType()) {
            
            return false;
          }
          if (!hasLiveId()) {
            
            return false;
          }
          if (!hasDemandType()) {
            
            return false;
          }
          if (!hasDemandId()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int liveType_ ;
        /**
         * <code>required uint32 LiveType = 1;</code>
         *
         * <pre>
         * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
         * </pre>
         */
        public boolean hasLiveType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 LiveType = 1;</code>
         *
         * <pre>
         * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
         * </pre>
         */
        public int getLiveType() {
          return liveType_;
        }
        /**
         * <code>required uint32 LiveType = 1;</code>
         *
         * <pre>
         * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
         * </pre>
         */
        public Builder setLiveType(int value) {
          bitField0_ |= 0x00000001;
          liveType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 LiveType = 1;</code>
         *
         * <pre>
         * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
         * </pre>
         */
        public Builder clearLiveType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          liveType_ = 0;
          onChanged();
          return this;
        }

        private int liveId_ ;
        /**
         * <code>required uint32 LiveId = 2;</code>
         */
        public boolean hasLiveId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required uint32 LiveId = 2;</code>
         */
        public int getLiveId() {
          return liveId_;
        }
        /**
         * <code>required uint32 LiveId = 2;</code>
         */
        public Builder setLiveId(int value) {
          bitField0_ |= 0x00000002;
          liveId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 LiveId = 2;</code>
         */
        public Builder clearLiveId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          liveId_ = 0;
          onChanged();
          return this;
        }

        private int demandType_ ;
        /**
         * <code>required uint32 DemandType = 3;</code>
         *
         * <pre>
         * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
         * </pre>
         */
        public boolean hasDemandType() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required uint32 DemandType = 3;</code>
         *
         * <pre>
         * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
         * </pre>
         */
        public int getDemandType() {
          return demandType_;
        }
        /**
         * <code>required uint32 DemandType = 3;</code>
         *
         * <pre>
         * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
         * </pre>
         */
        public Builder setDemandType(int value) {
          bitField0_ |= 0x00000004;
          demandType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 DemandType = 3;</code>
         *
         * <pre>
         * 1代表未知; 2代表Window; 3代表Android; 4代表ios; 5代表mac; 6代表linux.
         * </pre>
         */
        public Builder clearDemandType() {
          bitField0_ = (bitField0_ & ~0x00000004);
          demandType_ = 0;
          onChanged();
          return this;
        }

        private int demandId_ ;
        /**
         * <code>required uint32 DemandId = 4;</code>
         */
        public boolean hasDemandId() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required uint32 DemandId = 4;</code>
         */
        public int getDemandId() {
          return demandId_;
        }
        /**
         * <code>required uint32 DemandId = 4;</code>
         */
        public Builder setDemandId(int value) {
          bitField0_ |= 0x00000008;
          demandId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 DemandId = 4;</code>
         */
        public Builder clearDemandId() {
          bitField0_ = (bitField0_ & ~0x00000008);
          demandId_ = 0;
          onChanged();
          return this;
        }

        private int toDemandId_ ;
        /**
         * <code>optional uint32 ToDemandId = 5;</code>
         */
        public boolean hasToDemandId() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional uint32 ToDemandId = 5;</code>
         */
        public int getToDemandId() {
          return toDemandId_;
        }
        /**
         * <code>optional uint32 ToDemandId = 5;</code>
         */
        public Builder setToDemandId(int value) {
          bitField0_ |= 0x00000010;
          toDemandId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 ToDemandId = 5;</code>
         */
        public Builder clearToDemandId() {
          bitField0_ = (bitField0_ & ~0x00000010);
          toDemandId_ = 0;
          onChanged();
          return this;
        }

        private int toDemandType_ ;
        /**
         * <code>optional uint32 ToDemandType = 6;</code>
         */
        public boolean hasToDemandType() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional uint32 ToDemandType = 6;</code>
         */
        public int getToDemandType() {
          return toDemandType_;
        }
        /**
         * <code>optional uint32 ToDemandType = 6;</code>
         */
        public Builder setToDemandType(int value) {
          bitField0_ |= 0x00000020;
          toDemandType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 ToDemandType = 6;</code>
         */
        public Builder clearToDemandType() {
          bitField0_ = (bitField0_ & ~0x00000020);
          toDemandType_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:CommonProtocol.LiveCommonHeader)
      }

      static {
        defaultInstance = new LiveCommonHeader(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:CommonProtocol.LiveCommonHeader)
    }

    private int bitField0_;
    public static final int COMMHEADER_FIELD_NUMBER = 1;
    private com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader commHeader_;
    /**
     * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public boolean hasCommHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader getCommHeader() {
      return commHeader_;
    }
    /**
     * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
     */
    public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeaderOrBuilder getCommHeaderOrBuilder() {
      return commHeader_;
    }

    public static final int LIVEHEADER_FIELD_NUMBER = 2;
    private com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader liveHeader_;
    /**
     * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public boolean hasLiveHeader() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader getLiveHeader() {
      return liveHeader_;
    }
    /**
     * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
     */
    public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeaderOrBuilder getLiveHeaderOrBuilder() {
      return liveHeader_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes Data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes Data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      commHeader_ = com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.getDefaultInstance();
      liveHeader_ = com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.getDefaultInstance();
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLiveHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCommHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getLiveHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, commHeader_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, liveHeader_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, commHeader_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, liveHeader_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommonProtocol}
     *
     * <pre>
     *公共头
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommonProtocol)
        com.lianggzone.netty.entity.ProtocolModule.CommonProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.class, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.Builder.class);
      }

      // Construct using com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCommHeaderFieldBuilder();
          getLiveHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (commHeaderBuilder_ == null) {
          commHeader_ = com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.getDefaultInstance();
        } else {
          commHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (liveHeaderBuilder_ == null) {
          liveHeader_ = com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.getDefaultInstance();
        } else {
          liveHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lianggzone.netty.entity.ProtocolModule.internal_static_CommonProtocol_descriptor;
      }

      public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol getDefaultInstanceForType() {
        return com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.getDefaultInstance();
      }

      public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol build() {
        com.lianggzone.netty.entity.ProtocolModule.CommonProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol buildPartial() {
        com.lianggzone.netty.entity.ProtocolModule.CommonProtocol result = new com.lianggzone.netty.entity.ProtocolModule.CommonProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (commHeaderBuilder_ == null) {
          result.commHeader_ = commHeader_;
        } else {
          result.commHeader_ = commHeaderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (liveHeaderBuilder_ == null) {
          result.liveHeader_ = liveHeader_;
        } else {
          result.liveHeader_ = liveHeaderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lianggzone.netty.entity.ProtocolModule.CommonProtocol) {
          return mergeFrom((com.lianggzone.netty.entity.ProtocolModule.CommonProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol other) {
        if (other == com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.getDefaultInstance()) return this;
        if (other.hasCommHeader()) {
          mergeCommHeader(other.getCommHeader());
        }
        if (other.hasLiveHeader()) {
          mergeLiveHeader(other.getLiveHeader());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommHeader()) {
          
          return false;
        }
        if (!hasLiveHeader()) {
          
          return false;
        }
        if (!getCommHeader().isInitialized()) {
          
          return false;
        }
        if (!getLiveHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lianggzone.netty.entity.ProtocolModule.CommonProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lianggzone.netty.entity.ProtocolModule.CommonProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader commHeader_ = com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.Builder, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeaderOrBuilder> commHeaderBuilder_;
      /**
       * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
       */
      public boolean hasCommHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
       */
      public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader getCommHeader() {
        if (commHeaderBuilder_ == null) {
          return commHeader_;
        } else {
          return commHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
       */
      public Builder setCommHeader(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader value) {
        if (commHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          commHeader_ = value;
          onChanged();
        } else {
          commHeaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
       */
      public Builder setCommHeader(
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.Builder builderForValue) {
        if (commHeaderBuilder_ == null) {
          commHeader_ = builderForValue.build();
          onChanged();
        } else {
          commHeaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
       */
      public Builder mergeCommHeader(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader value) {
        if (commHeaderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              commHeader_ != com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.getDefaultInstance()) {
            commHeader_ =
              com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.newBuilder(commHeader_).mergeFrom(value).buildPartial();
          } else {
            commHeader_ = value;
          }
          onChanged();
        } else {
          commHeaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
       */
      public Builder clearCommHeader() {
        if (commHeaderBuilder_ == null) {
          commHeader_ = com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.getDefaultInstance();
          onChanged();
        } else {
          commHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
       */
      public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.Builder getCommHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCommHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
       */
      public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeaderOrBuilder getCommHeaderOrBuilder() {
        if (commHeaderBuilder_ != null) {
          return commHeaderBuilder_.getMessageOrBuilder();
        } else {
          return commHeader_;
        }
      }
      /**
       * <code>required .CommonProtocol.CommonHeader CommHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.Builder, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeaderOrBuilder> 
          getCommHeaderFieldBuilder() {
        if (commHeaderBuilder_ == null) {
          commHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeader.Builder, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.CommonHeaderOrBuilder>(
                  getCommHeader(),
                  getParentForChildren(),
                  isClean());
          commHeader_ = null;
        }
        return commHeaderBuilder_;
      }

      private com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader liveHeader_ = com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.Builder, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeaderOrBuilder> liveHeaderBuilder_;
      /**
       * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
       */
      public boolean hasLiveHeader() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
       */
      public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader getLiveHeader() {
        if (liveHeaderBuilder_ == null) {
          return liveHeader_;
        } else {
          return liveHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
       */
      public Builder setLiveHeader(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader value) {
        if (liveHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          liveHeader_ = value;
          onChanged();
        } else {
          liveHeaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
       */
      public Builder setLiveHeader(
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.Builder builderForValue) {
        if (liveHeaderBuilder_ == null) {
          liveHeader_ = builderForValue.build();
          onChanged();
        } else {
          liveHeaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
       */
      public Builder mergeLiveHeader(com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader value) {
        if (liveHeaderBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              liveHeader_ != com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.getDefaultInstance()) {
            liveHeader_ =
              com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.newBuilder(liveHeader_).mergeFrom(value).buildPartial();
          } else {
            liveHeader_ = value;
          }
          onChanged();
        } else {
          liveHeaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
       */
      public Builder clearLiveHeader() {
        if (liveHeaderBuilder_ == null) {
          liveHeader_ = com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.getDefaultInstance();
          onChanged();
        } else {
          liveHeaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
       */
      public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.Builder getLiveHeaderBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLiveHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
       */
      public com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeaderOrBuilder getLiveHeaderOrBuilder() {
        if (liveHeaderBuilder_ != null) {
          return liveHeaderBuilder_.getMessageOrBuilder();
        } else {
          return liveHeader_;
        }
      }
      /**
       * <code>required .CommonProtocol.LiveCommonHeader LiveHeader = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.Builder, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeaderOrBuilder> 
          getLiveHeaderFieldBuilder() {
        if (liveHeaderBuilder_ == null) {
          liveHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeader.Builder, com.lianggzone.netty.entity.ProtocolModule.CommonProtocol.LiveCommonHeaderOrBuilder>(
                  getLiveHeader(),
                  getParentForChildren(),
                  isClean());
          liveHeader_ = null;
        }
        return liveHeaderBuilder_;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes Data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes Data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes Data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes Data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CommonProtocol)
    }

    static {
      defaultInstance = new CommonProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CommonProtocol)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CommonProtocol_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonProtocol_CommonHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CommonProtocol_CommonHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonProtocol_LiveCommonHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CommonProtocol_LiveCommonHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/ProtocolModule.proto\"\341\002\n\016CommonP" +
      "rotocol\0220\n\nCommHeader\030\001 \002(\0132\034.CommonProt" +
      "ocol.CommonHeader\0224\n\nLiveHeader\030\002 \002(\0132 ." +
      "CommonProtocol.LiveCommonHeader\022\014\n\004Data\030" +
      "\003 \001(\014\032R\n\014CommonHeader\022\021\n\tCommandId\030\001 \002(\r" +
      "\022\r\n\005SeqId\030\002 \002(\r\022\017\n\007Version\030\003 \002(\r\022\017\n\007From" +
      "Uid\030\004 \001(\t\032\204\001\n\020LiveCommonHeader\022\020\n\010LiveTy" +
      "pe\030\001 \002(\r\022\016\n\006LiveId\030\002 \002(\r\022\022\n\nDemandType\030\003" +
      " \002(\r\022\020\n\010DemandId\030\004 \002(\r\022\022\n\nToDemandId\030\005 \001" +
      "(\r\022\024\n\014ToDemandType\030\006 \001(\rB-\n\033com.lianggzo",
      "ne.netty.entityB\016ProtocolModule"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CommonProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommonProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CommonProtocol_descriptor,
        new java.lang.String[] { "CommHeader", "LiveHeader", "Data", });
    internal_static_CommonProtocol_CommonHeader_descriptor =
      internal_static_CommonProtocol_descriptor.getNestedTypes().get(0);
    internal_static_CommonProtocol_CommonHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CommonProtocol_CommonHeader_descriptor,
        new java.lang.String[] { "CommandId", "SeqId", "Version", "FromUid", });
    internal_static_CommonProtocol_LiveCommonHeader_descriptor =
      internal_static_CommonProtocol_descriptor.getNestedTypes().get(1);
    internal_static_CommonProtocol_LiveCommonHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CommonProtocol_LiveCommonHeader_descriptor,
        new java.lang.String[] { "LiveType", "LiveId", "DemandType", "DemandId", "ToDemandId", "ToDemandType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
